# Generated by Django 5.1.1 on 2024-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'بازی', 'verbose_name_plural': 'بازی'},
        ),
        migrations.AlterModelOptions(
            name='gamedetails',
            options={'verbose_name': 'صفحه ی توضیحات', 'verbose_name_plural': 'صفحه توضیحات بازی'},
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام بازی'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='description',
            field=models.TextField(verbose_name='توضیحات کامل بازی'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='image1',
            field=models.ImageField(upload_to='images/', verbose_name='تصویر اول'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='image2',
            field=models.ImageField(upload_to='images/', verbose_name='تصویر دوم'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='image3',
            field=models.ImageField(upload_to='images/', verbose_name='تصویر سوم'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام بازی'),
        ),
    ]
