# Generated by Django 5.1.1 on 2024-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='تصویر اول'),
        ),
        migrations.AddField(
            model_name='game',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='تصویر دوم'),
        ),
        migrations.AddField(
            model_name='game',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='تصویر سوم'),
        ),
        migrations.AddField(
            model_name='game',
            name='long_description',
            field=models.TextField(null=True, verbose_name='توضیحات کامل بازی'),
        ),
    ]
