# Generated by Django 5.1.1 on 2024-09-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_file_size_alter_game_image1_alter_game_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link_file',
            field=models.TextField(blank=True, null=True, verbose_name='لینک سایت'),
        ),
    ]
